# Generated by Django 4.2 on 2024-11-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UCL_history_finals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='Unknown Season', max_length=50)),
                ('team', models.CharField(default='Unknown Team', max_length=50)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('match_venue', models.CharField(default='Unknown Venue', max_length=50)),
                ('match_notes', models.CharField(default='No Notes', max_length=50)),
                ('result', models.CharField(default='Unknown Result', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UCL_history_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('team', models.CharField(default='Unknown Team', max_length=50)),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
            ],
        ),
    ]
